### ISSUE TITLE
Error: Converting circular structure to JSON

### ISSUE THREAD

**Issue by xEcEz** [fubhy/graphql-transport-electron#11]
Is the library working with `@apollo/client` v3? I see it still uses the `apollo-http` lib that was relocated to `@apollo/client`.

Following the getting started, I have a similar setup where I create an IpcExecutor that uses an HttpLink pointing to my remote server and a IpcLink in the renderer process that is passed to my ApolloClient. I get the following error:

main:
```
const link = new HttpLink({ uri: 'http://localhost:4000/graphql', fetch });
createIpcExecutor({ link, ipc: ipcMain });
```

renderer:
```
const link = createIpcLink({ ipc: ipcRenderer });
// const link = new HttpLink({ uri: 'http://localhost:4000/graphql' });
const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  link
});

const AppContainer = process.env.PLAIN_HMR ? Fragment : ReactHotAppContainer;

document.addEventListener('DOMContentLoaded', () =>
  render(
    <AppContainer>
      <Root store={store} history={history} apolloClient={apolloClient} />
    </AppContainer>,
    document.getElementById('root')
  )
);
```

stack:
```
Error: Converting circular structure to JSON
    --> starting at object with constructor 'InMemoryCache'
    |     property 'policies' -> object with constructor 'Policies'
    |     property 'config' -> object with constructor 'Object'
    --- property 'cache' closes the circle
    at new ApolloError (http://localhost:1212/dist/renderer.dev.js:14968:28)
    at ObservableQuery.module.exports../node_modules/@apollo/client/core/ObservableQuery.js.ObservableQuery.getCurrentResult (http://localhost:1212/dist/renderer.dev.js:13337:28)
    at QueryData._this.getQueryResult (http://localhost:1212/dist/renderer.dev.js:16708:61)
    at QueryData.module.exports../node_modules/@apollo/client/react/data/QueryData.js.QueryData.getExecuteResult (http://localhost:1212/dist/renderer.dev.js:16827:27)
    at QueryData.module.exports../node_modules/@apollo/client/react/data/QueryData.js.QueryData.execute (http://localhost:1212/dist/renderer.dev.js:16776:51)
    at http://localhost:1212/dist/renderer.dev.js:17342:151
    at useDeepMemo (http://localhost:1212/dist/renderer.dev.js:17386:42)
    at useBaseQuery (http://localhost:1212/dist/renderer.dev.js:17342:85)
    at useQuery (http://localhost:1212/dist/renderer.dev.js:17228:87)
    at LoginView (http://localhost:1212/dist/renderer.dev.js:10093:76)
```

Note that if I pass an HttpLink created in the render process to my ApolloClient, things work as expected. Am I missing anything?

**Comment by xEcEz** [comment]
Seems like this is the issue:

https://github.com/fubhy/graphql-transport-electron/blob/7e76213b9f5ecc10c35d0765fac78d0db1883070/src/client.ts#L32

**Comment by fubhy** [comment]
It seems like we should allow passing a context serializer as a callback to the ApolloIpcLink options. That way, by default we could simply ignore the context (`context: undefined`) but allow implementations that depend on it to send custom values to the main process to control how they are serialized.

Would you mind submitting a PR for this? You could also consider upgrading the dependencies for apollo to v3. I currently don't use this library myself so would appreciate a PR for this! Thanks

**Comment by megahertz** [comment]
While we're waiting for merging the PR above, here's a monkey patch

**IpcLinkPatched.ts**
```typescript
/* eslint-disable */

import { FetchResult, Observable, Operation } from '@apollo/client';
import { print } from 'graphql';
import { IpcLink as IpcLinkOriginal } from 'graphql-transport-electron';

// @ts-ignore
export class IpcLink extends IpcLinkOriginal {
  private counter;
  private observers;
  private ipc;
  private channel;

  request(operation: Operation): any {
    return new Observable(
      (observer: ZenObservable.SubscriptionObserver<FetchResult>) => {
        const current = `${++this.counter}`;
        const request = {
          operationName: operation.operationName,
          variables: operation.variables,
          query: print(operation.query),
          context: JSON.parse(
            JSON.stringify(operation.getContext(), createSerializer())
          ),
        };

        this.observers.set(current, observer);
        this.ipc.send(this.channel, current, request);
      },
    );
  }
}

export function createIpcLink(options) {
  return new IpcLink(options);
}

function createSerializer() {
  var seen = new WeakSet();

  return function (key, value) {
    if (typeof value === 'object' && value !== null) {
      if (seen.has(value)) {
        return undefined;
      }

      seen.add(value);
    }

    return value;
  };
}
```

**Comment by megahertz** [comment]
@fubhy could you please review the PR made by @xEcEz ?

**Comment by fubhy** [comment]
Sorry for the delay. I am currently not actively using this myself. I reviewed & merged it and updated some dependencies along the way. Tagged v2.0.0 including this.
